apiVersion: v1
kind: Service
metadata:
  name: docker-tabloid
  labels:
    app:  docker-tabloid
spec:
  selector:
    app: docker-tabloid
  ports:
    - protocol: "TCP"
      port: 8080 # where the service is running
      targetPort: 8080 # the port exposed by the service
  type: NodePort # type of service